version: "3.8"

services:
  mongodb:
    build: ./mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks:
      - app-network

  login-service:
    build:
      context: ./login
      args:
        MONGODB_IP: mongodb
    container_name: login-app
    ports:
      - "8000:80"
    depends_on:
      - mongodb
    restart: unless-stopped
    environment:
      - MONGODB_IP=mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
